# Generated by Django 3.2.6 on 2021-08-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('N', 'Not Featured'), ('P', 'Primary'), ('S', 'Secondary')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Publish')], default='D', max_length=1),
        ),
    ]
