# Generated by Django 3.2.6 on 2021-08-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210824_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('S', 'Secondary'), ('N', 'Not Featured'), ('P', 'Primary')], default='N', max_length=1),
        ),
    ]
