# Generated by Django 3.2.6 on 2021-08-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MKT', 'Marketing'), ('3DP', 'Printing 3D'), ('FPV', 'Fpv Drones'), ('WII', 'Portablizing'), ('DEV', 'Web Development'), ('COD', 'Other Coding'), ('TKR', 'Other Electronics'), ('SKI', 'Outdoors'), ('STZ', 'Style')], default='DEV', max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('None', 'Not Featured')], default='None', max_length=4),
        ),
    ]
