# Generated by Django 3.2.6 on 2021-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210824_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('3D Printing', 'Printing 3D'), ('FPV Drones', 'Fpv Drones'), ('Portablizing', 'Portablizing'), ('Web Development', 'Web Development'), ('Other Coding', 'Other Coding'), ('Other Electronics', 'Other Electronics'), ('Outdoors', 'Outdoors'), ('Style', 'Style')], default='Web Development', max_length=20),
        ),
    ]
