# Generated by Django 3.2.6 on 2021-08-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('3D Printing', 'Printing 3D'), ('FPV Drones', 'Fpv Drones'), ('Portablizing', 'Portablizing'), ('Web Development', 'Web Development'), ('Other Coding', 'Other Coding'), ('Other Electronics', 'Other Electronics'), ('Outdoors', 'Outdoors'), ('Style', 'Style'), ('Kids', 'Kids')], default='Web Development', max_length=20),
        ),
    ]
