# Generated by Django 3.2.6 on 2021-08-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210825_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.CharField(default='Blog preview text goes here', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MKT', 'Marketing'), ('P3D', '3D Printing'), ('FPV', 'FPV Drones'), ('WII', 'Portables'), ('WEB', 'Web Development'), ('COD', 'Other Coding'), ('OEE', 'Other Electronics'), ('SKI', 'Outdoors'), ('STZ', 'Style'), ('KID', 'Kids')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MKT', 'Marketing'), ('P3D', '3D Printing'), ('FPV', 'FPV Drones'), ('WII', 'Portables'), ('WEB', 'Web Development'), ('COD', 'Other Coding'), ('OEE', 'Other Electronics'), ('SKI', 'Outdoors'), ('STZ', 'Style'), ('KID', 'Kids')], default='WEB', max_length=20),
        ),
    ]
