# Generated by Django 3.2.6 on 2021-08-25 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210825_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_primary',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_secondary',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('N', 'Not Featured')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MKT', 'Marketing'), ('P3D', '3D Printing'), ('FPV', 'FPV Drones'), ('WII', 'Portables'), ('WEB', 'Web Development'), ('COD', 'Other Coding'), ('OEE', 'Other Electronics'), ('SKI', 'Outdoors'), ('STZ', 'Style'), ('KID', 'Kids')], default='WEB', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
