# Generated by Django 3.2.6 on 2021-08-28 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MKT', 'Marketing'), ('P3D', '3D Printing'), ('FPV', 'FPV Drones'), ('WII', 'Portables'), ('WEB', 'Web Development'), ('COD', 'Other Coding'), ('OEE', 'Other Electronics'), ('SKI', 'Outdoors'), ('SPT', 'Sports'), ('KID', 'Kids')], max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MKT', 'Marketing'), ('P3D', '3D Printing'), ('FPV', 'FPV Drones'), ('WII', 'Portables'), ('WEB', 'Web Development'), ('COD', 'Other Coding'), ('OEE', 'Other Electronics'), ('SKI', 'Outdoors'), ('SPT', 'Sports'), ('KID', 'Kids')], default='WEB', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
